### ISSUE TITLE
Latex source appears in grey but is not rendered in chrome

### ISSUE THREAD

**Issue by HaleTom** [iamcco/mathjax-support-for-mkdp#3]
`:echo g:mathjax_vim_path` gives:
```
/home/ravi/.local/share/vim/bundle/mathjax-support-for-mkdp/mathjax-static/
```

But when I try to view the latex what appears between `$` characters is instead displayed in grey/gray:

![Latex in gray](https://imgur.com/LywBjIGl.png)

Here is the source:

```
Additionally, for classification, the *0/1 misclassifiction error* can be used:

$$err(h_\Theta(x),y) = \begin{cases} 1 & \mbox{if } h_\Theta(x) \geq 0.5\ and\ y = 0\ or\ h_\Theta(x) < 0.5\ and\ y = 1\newline 0 & \mbox otherwise \end{cases}$$

This gives us a binary 0 or 1 error result based on a misclassification. The average test error for the test set is:

$$\text{Test Error} = \dfrac{1}{m_{test}} \sum^{m_{test}}_{i=1} err(h_\Theta(x^{(i)}_{test}), y^{(i)}_{test})$$

This gives us the proportion of the test data that was misclassified.
```

MathJax on other pages such as this [test page](http://www.cs.toronto.edu/~yujiali/test/mathjax.html) appears fine.

I can't right-click on the grey text and change the renderer. The standard context menu appears, rather than the Mathjax context menu.

**Comment by sadid** [comment]
Same here. I can totally reproduce @HaleTom issue. I've installed both extension and `echo g:mathjax_vim_path` gives:

```
/home/sadid/CCnf/Vim/.vim/plugged/mathjax-support-for-mkdp/mathjax-static/
```

**Comment by HaleTom** [comment]
@sadid I followed [this answer](https://superuser.com/a/1241704/365890) which resolved it for me.
